version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: sequelize
    versions:
    - 6.5.1
    - 6.6.0
    - 6.6.1
  - dependency-name: sqlite3
    versions:
    - 5.0.1
